" Forces vim functionality even if vimrc is not used.
set nocompatible

" ================
" Syntax
" ================

" Turn on syntax highlighting.
syntax on

" Adjust tab spacing from a width of 8 to 4 and making them spaces
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

" Enable filetype exclusive settings:
filetype plugin indent on

" Auto indents code
" set autoindent

" ================
" Editor Settings
" ================

" Disable the default Vim startup message.
set shortmess+=I

" Show line numbers.
set number

" Enables relative line numbering mode.
set relativenumber

" Always show the status line at the bottom, even if you only have one window open.
set laststatus=2

" Change backspace for it to be more workable
set backspace=indent,eol,start

" Turn on hidden buffers
set hidden

" Set up case-insensitivity for searching text
set ignorecase
set smartcase

" Enable searching as you type
set incsearch

" Unbind some useless/annoying default key bindings.
nmap Q <Nop> " 'Q' in normal mode enters Ex mode. You almost never want this.

" Disable audible bell
set noerrorbells visualbell t_vb=

" Enable mouse support.
set mouse+=a

" ================
" Keybinds
" ================

" Disables arrow keys to forcibly use h/j/k/l
" Do this in normal mode...
nnoremap <Left>  :echoe "Use h"<CR>
nnoremap <Right> :echoe "Use l"<CR>
nnoremap <Up>    :echoe "Use k"<CR>
nnoremap <Down>  :echoe "Use j"<CR>
" ...and in insert mode
inoremap <Left>  <ESC>:echoe "Use h"<CR>
inoremap <Right> <ESC>:echoe "Use l"<CR>
inoremap <Up>    <ESC>:echoe "Use k"<CR>
inoremap <Down>  <ESC>:echoe "Use j"<CR>
" ...and in visual mode
vnoremap <Left>  <ESC>:echoe "Use h"<CR>
vnoremap <Right> <ESC>:echoe "Use l"<CR>
vnoremap <Up>    <ESC>:echoe "Use k"<CR>
vnoremap <Down>  <ESC>:echoe "Use j"<CR>

" Keybind to use the CtrlP plugin
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'

" Disable keybinds for Tmux
map <C-a> <Nop>
